version: '2'
services:
  app:
    build: .
    ports:
      - "9000:9000"
    environment:
      - MONGODB_URI_DEFAULT=mongodb://db:27017/clotho
    links:
      - db
  db:
    image: mongo
    ports:
      - "27018:27017"
