version: 2
jobs:
  build:
    working_directory: ~/clotho
    environment:
      - NODE_ENV: test
    docker:
      - image: node:6.11.0
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: npm test
