version: 2
jobs:
  build:
    working_directory: ~/clotho
    docker:
      - image: lukyth/node-firebase-rsync
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: Add ssh key to know_hosts
          command: ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                rm -rf node_modules && rsync -r ./* circleci@$SERVER_IP:/home/circleci/clotho/
                ssh circleci@$SERVER_IP 'cd /home/circleci/clotho && docker-compose build && docker-compose up -d'
              fi
