version: 2
jobs:
  build:
    working_directory: ~/clotho
    docker:
      - image: lukyth/node-firebase-rsync
      - image: mongo:3.4.4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - .node_modules
      - run:
          name: test
          command: npm test
      - deploy:
          name: Deploy
          command: |
                rm -rf node_modules && rsync -r ./* circleci@$SERVER_IP:/home/circleci/$CIRCLE_PROJECT_REPONAME/production/
                ssh circleci@$SERVER_IP 'cd /home/circleci/$CIRCLE_PROJECT_REPONAME/production/ && docker-compose build && docker-compose up -d'
